// Bake bearings into a generated module. Workers have no filesystem, so the raw
// bearing YAML is embedded at build time; the Worker parses it with
// parseBearing at cold start (CLAUDE.md: "Content is baked into a generated
// module at build time"). loadBearing is a build-time-only helper — used here,
// never shipped to the Worker.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const fixtures = resolve(here, '../../../packages/core/src/fixtures')

// Spike: serve the two v2 example bearings. M2 will bake a real bearing set.
const files = ['standing-example.yaml', 'journey-example.yaml']
const sources = files.map((f) => readFileSync(resolve(fixtures, f), 'utf8'))

const out = `// GENERATED by scripts/bake.mjs — do not edit.
// Raw bearing YAML baked at build time; the Worker parses these with
// parseBearing at cold start (Workers have no filesystem).
export const BEARING_SOURCES: string[] = ${JSON.stringify(sources, null, 2)}
`

writeFileSync(resolve(here, '../src/bearings.generated.ts'), out)
console.log(`baked ${sources.length} bearings from ${files.join(', ')}`)
